# Generated by Django 2.1.2 on 2018-10-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa', '0002_report_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='_range',
        ),
        migrations.AlterField(
            model_name='report',
            name='remarks',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
