# Generated by Django 2.1.2 on 2018-10-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa', '0003_auto_20181021_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
